name: Factorio
version: 1.0
authors: [Alek05, MartinErSej]
api-version: 1.13
main: dk.superawesome.factorio.Factorio
soft-depend: [ChestShop]

commands:
  addmembertoall:
    usage: /addmembertoall <spiller>
    description: Tilføj en spiller som medlem til alle dine maskiner.
  removememberfromall:
    usage: /removememberfromall <spiller>
    description: Fjern en spiller som medlem fra alle dine maskiner.
  listdefaultmembers:
    usage: /listdefaultmembers
    description: Se en liste af alle standard medlemmer af dine nybyggede maskiner.
  adddefaultmember:
    usage: /adddefaultmember <spiller>
    description: Tilføj en spiller som standard medlem af dine nybyggede maskiner.
  removedefaultmember:
    usage: /removedefaultmember <spiller>
    description: Fjern en spiller som standard medlem af dine nybyggede maskiner.
  addmember:
    usage: /addmember <spiller>
    description: Tilføj en spiller som medlem af en maskine.
  removemember:
    usage: /removemember <spiller>
    description: Fjern en spiller som medlem fra en maskine.
  debug:
    permission: factorio.debug
    permission-message: Du har ikke adgang til dette kommando.
    usage: /debug
    description: Debug kommando.